apiVersion: 1

deleteDatasources:
  - name: Codestra Prometheus
    orgId: 1
  - name: Codestra Loki
    orgId: 1
  - name: Codestra Tempo
    orgId: 1
  - name: Codestra Alertmanager
    orgId: 1

datasources:
  - name: Codestra Prometheus
    uid: codestra-prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
    jsonData:
      httpMethod: POST
      timeInterval: 30s
      prometheusType: Prometheus
      prometheusVersion: "3"
      exemplarTraceIdDestinations:
        - name: trace_id
          datasourceUid: codestra-tempo

  - name: Codestra Loki
    uid: codestra-loki
    type: loki
    access: proxy
    url: http://loki:3100
    editable: false
    jsonData:
      maxLines: 5000
      httpHeaderName1: X-Scope-OrgID
      derivedFields:
        - name: TraceID
          matcherRegex: '"trace_id":"([a-fA-F0-9]+)"'
          datasourceUid: codestra-tempo
          url: '$${__value.raw}'
    secureJsonData:
      httpHeaderValue1: codestra

  - name: Codestra Tempo
    uid: codestra-tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    editable: false
    jsonData:
      httpHeaderName1: X-Scope-OrgID
      nodeGraph:
        enabled: true
      serviceMap:
        datasourceUid: codestra-prometheus
      tracesToLogsV2:
        datasourceUid: codestra-loki
        spanStartTimeShift: -5m
        spanEndTimeShift: 5m
        filterByTraceID: true
        filterBySpanID: false
    secureJsonData:
      httpHeaderValue1: codestra

  - name: Codestra Alertmanager
    uid: codestra-alertmanager
    type: alertmanager
    access: proxy
    url: http://alertmanager:9093
    editable: false
    jsonData:
      implementation: prometheus
      handleGrafanaManagedAlerts: false
